Running from arcus-8
2019-05-16 14:48:03.281437: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-16 14:48:04.149794: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:02:00.0
totalMemory: 11.91GiB freeMemory: 11.75GiB
2019-05-16 14:48:04.149834: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-16 14:48:16.392192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-16 14:48:16.392515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-16 14:48:16.392540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-16 14:48:16.393141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11374 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0, compute capability: 6.1)
{'alpha': 0.6003585488784566, 'dropout': 0.4493451367352536, 'lr': 0.003609000867395369, 'leaky_relu': 0.030742230414359473, 'batch_norm': 0, 'num_layers': 4, 'layer_0': 453, 'layer_1': 47, 'layer_2': 389, 'layer_3': 444, 'layer_4': 390, 'layer_5': 323, 'layer_6': 471, 'layer_7': 472, 'max_concurrent': 3, 'P': 'arcus_gpu.p', 'q': 'arcus.q', 'l': "hostname='(arcus-1|arcus-2|arcus-3|arcus-4|arcus-5|arcus-6|arcus-7|arcus-8|arcus-9|arcus-10)'", 'env': '/home/jott1/Projects/SHERPA_EX/.profile', 'data': 'fluxbypass_aqua', 'net_type': 'conservation', 'loss_type': 'mse', 'batch_size': 2048, 'data_dir': '/baldig/chemistry/earth_system_science/', 'max_dense_layers': 8, 'epochs': 25, 'patience': 10}
Epoch 1/25
 - 3032s - loss: 391.4031 - mean_squared_error: 391.4031 - val_loss: 400.6457 - val_mean_squared_error: 400.6457
Epoch 2/25
 - 3191s - loss: 313.8984 - mean_squared_error: 313.8984 - val_loss: 293.3726 - val_mean_squared_error: 293.3726
Epoch 3/25
 - 3258s - loss: 303.8339 - mean_squared_error: 303.8339 - val_loss: 365.5800 - val_mean_squared_error: 365.5800
Epoch 4/25
 - 3253s - loss: 299.7622 - mean_squared_error: 299.7622 - val_loss: 348.6473 - val_mean_squared_error: 348.6473
Epoch 5/25
 - 3604s - loss: 295.8667 - mean_squared_error: 295.8667 - val_loss: 390.6051 - val_mean_squared_error: 390.6051
Epoch 6/25
 - 3350s - loss: 292.1540 - mean_squared_error: 292.1540 - val_loss: 404.6105 - val_mean_squared_error: 404.6105
Epoch 7/25
 - 3472s - loss: 289.7440 - mean_squared_error: 289.7440 - val_loss: 406.4191 - val_mean_squared_error: 406.4191
Epoch 8/25
 - 3264s - loss: 288.2263 - mean_squared_error: 288.2263 - val_loss: 365.0431 - val_mean_squared_error: 365.0431
Epoch 9/25
 - 3555s - loss: 286.8564 - mean_squared_error: 286.8564 - val_loss: 377.2973 - val_mean_squared_error: 377.2973
Epoch 10/25
 - 3383s - loss: 285.9448 - mean_squared_error: 285.9448 - val_loss: 384.2442 - val_mean_squared_error: 384.2442
Epoch 11/25
 - 4708s - loss: 284.9807 - mean_squared_error: 284.9807 - val_loss: 351.4953 - val_mean_squared_error: 351.4953
Epoch 12/25
 - 3683s - loss: 284.1430 - mean_squared_error: 284.1430 - val_loss: 351.6941 - val_mean_squared_error: 351.6941
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 12
