Running from arcus-8
2019-05-17 13:34:17.234468: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-17 13:34:18.745727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:03:00.0
totalMemory: 11.91GiB freeMemory: 11.75GiB
2019-05-17 13:34:18.745782: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-17 13:34:33.046809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-17 13:34:33.047339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-17 13:34:33.047362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-17 13:34:33.047893: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11374 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:03:00.0, compute capability: 6.1)
Epoch 1/25
 - 4026s - loss: 314.2352 - mean_squared_error: 314.2352 - val_loss: 211.6990 - val_mean_squared_error: 211.6990
Epoch 2/25
 - 4602s - loss: 256.1205 - mean_squared_error: 256.1205 - val_loss: 253.9765 - val_mean_squared_error: 253.9765
Epoch 3/25
 - 4652s - loss: 245.9982 - mean_squared_error: 245.9982 - val_loss: 259.3706 - val_mean_squared_error: 259.3706
Epoch 4/25
 - 3714s - loss: 240.6485 - mean_squared_error: 240.6485 - val_loss: 224.5171 - val_mean_squared_error: 224.5171
Epoch 5/25
 - 3933s - loss: 237.2297 - mean_squared_error: 237.2297 - val_loss: 202.0534 - val_mean_squared_error: 202.0534
Epoch 6/25
 - 3808s - loss: 234.9378 - mean_squared_error: 234.9378 - val_loss: 193.9812 - val_mean_squared_error: 193.9812
Epoch 7/25
 - 3879s - loss: 233.3799 - mean_squared_error: 233.3799 - val_loss: 196.9474 - val_mean_squared_error: 196.9474
Epoch 8/25
 - 4866s - loss: 231.7257 - mean_squared_error: 231.7257 - val_loss: 203.6053 - val_mean_squared_error: 203.6053
Epoch 9/25
 - 4237s - loss: 230.4253 - mean_squared_error: 230.4253 - val_loss: 205.5168 - val_mean_squared_error: 205.5168
Epoch 10/25
 - 6219s - loss: 229.5081 - mean_squared_error: 229.5081 - val_loss: 193.8603 - val_mean_squared_error: 193.8603
Epoch 11/25
 - 5699s - loss: 228.5474 - mean_squared_error: 228.5474 - val_loss: 200.2263 - val_mean_squared_error: 200.2263
Epoch 12/25
 - 4694s - loss: 227.7764 - mean_squared_error: 227.7764 - val_loss: 265.6606 - val_mean_squared_error: 265.6606
Epoch 13/25
 - 5206s - loss: 226.8832 - mean_squared_error: 226.8832 - val_loss: 211.1976 - val_mean_squared_error: 211.1976
Epoch 14/25
 - 5326s - loss: 226.1588 - mean_squared_error: 226.1588 - val_loss: 240.0350 - val_mean_squared_error: 240.0350
Epoch 15/25
 - 4484s - loss: 225.4866 - mean_squared_error: 225.4866 - val_loss: 247.9080 - val_mean_squared_error: 247.9080
Epoch 16/25
 - 5047s - loss: 224.9693 - mean_squared_error: 224.9693 - val_loss: 265.6411 - val_mean_squared_error: 265.6411
Epoch 17/25
 - 4361s - loss: 224.0321 - mean_squared_error: 224.0321 - val_loss: 212.1638 - val_mean_squared_error: 212.1638
Epoch 18/25
 - 4355s - loss: 223.3105 - mean_squared_error: 223.3105 - val_loss: 240.1328 - val_mean_squared_error: 240.1328
Epoch 19/25
 - 4132s - loss: 222.6782 - mean_squared_error: 222.6782 - val_loss: 210.1587 - val_mean_squared_error: 210.1587
Epoch 20/25
 - 4176s - loss: 222.2723 - mean_squared_error: 222.2723 - val_loss: 214.3466 - val_mean_squared_error: 214.3466
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 4
