2019-05-17 17:20:26.979235: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-17 17:20:30.410456: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX TITAN X major: 5 minor: 2 memoryClockRate(GHz): 1.076
pciBusID: 0000:02:00.0
totalMemory: 11.93GiB freeMemory: 11.60GiB
2019-05-17 17:20:30.410575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-17 17:20:35.742182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-17 17:20:35.742399: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-17 17:20:35.742432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-17 17:20:35.743516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11134 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:02:00.0, compute capability: 5.2)
Epoch 1/25
 - 7248s - loss: 974.9438 - mean_squared_error: 844.5826 - val_loss: 306.4407 - val_mean_squared_error: 401.4656
Epoch 2/25
 - 8717s - loss: 447.4119 - mean_squared_error: 376.5440 - val_loss: 273.0338 - val_mean_squared_error: 349.7561
Epoch 3/25
 - 7686s - loss: 370.6330 - mean_squared_error: 331.9717 - val_loss: 226.9775 - val_mean_squared_error: 306.2831
Epoch 4/25
 - 9683s - loss: 333.6465 - mean_squared_error: 312.6378 - val_loss: 394.7397 - val_mean_squared_error: 331.1999
Epoch 5/25
 - 9250s - loss: 312.0475 - mean_squared_error: 301.7301 - val_loss: 407.9832 - val_mean_squared_error: 362.8310
Epoch 6/25
 - 10246s - loss: 295.9671 - mean_squared_error: 294.3917 - val_loss: 362.0311 - val_mean_squared_error: 386.0304
Epoch 7/25
 - 8553s - loss: 284.4976 - mean_squared_error: 288.2765 - val_loss: 529.7802 - val_mean_squared_error: 381.3367
Epoch 8/25
 - 9466s - loss: 275.9836 - mean_squared_error: 283.6852 - val_loss: 418.4676 - val_mean_squared_error: 412.4055
Epoch 9/25
 - 10712s - loss: 269.1851 - mean_squared_error: 280.2483 - val_loss: 647.5574 - val_mean_squared_error: 390.9086
Epoch 10/25
 - 7331s - loss: 261.8639 - mean_squared_error: 277.0452 - val_loss: 428.9238 - val_mean_squared_error: 403.7730
Epoch 11/25
 - 7580s - loss: 256.5826 - mean_squared_error: 273.9403 - val_loss: 496.9858 - val_mean_squared_error: 438.8264
Epoch 12/25
 - 9198s - loss: 252.7630 - mean_squared_error: 271.8265 - val_loss: 459.7563 - val_mean_squared_error: 433.3652
Epoch 13/25
 - 8973s - loss: 249.1464 - mean_squared_error: 269.9891 - val_loss: 432.1729 - val_mean_squared_error: 429.6409
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 4
