2019-05-18 02:10:30.675009: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-18 02:10:31.006146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: TITAN V major: 7 minor: 0 memoryClockRate(GHz): 1.455
pciBusID: 0000:82:00.0
totalMemory: 11.75GiB freeMemory: 9.78GiB
2019-05-18 02:10:31.006197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-18 02:10:31.726886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-18 02:10:31.726945: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-18 02:10:31.726954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-18 02:10:31.727267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9429 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:82:00.0, compute capability: 7.0)
Epoch 1/25
 - 3311s - loss: 340.3606 - mean_squared_error: 340.3606 - val_loss: 244.1809 - val_mean_squared_error: 244.1809
Epoch 2/25
 - 691s - loss: 262.6734 - mean_squared_error: 262.6734 - val_loss: 263.3054 - val_mean_squared_error: 263.3054
Epoch 3/25
 - 2706s - loss: 250.2958 - mean_squared_error: 250.2958 - val_loss: 207.8868 - val_mean_squared_error: 207.8868
Epoch 4/25
 - 682s - loss: 244.3316 - mean_squared_error: 244.3316 - val_loss: 210.8647 - val_mean_squared_error: 210.8647
Epoch 5/25
 - 2676s - loss: 240.9359 - mean_squared_error: 240.9359 - val_loss: 199.1340 - val_mean_squared_error: 199.1340
Epoch 6/25
 - 682s - loss: 238.3593 - mean_squared_error: 238.3593 - val_loss: 243.1209 - val_mean_squared_error: 243.1209
Epoch 7/25
 - 3417s - loss: 236.7682 - mean_squared_error: 236.7682 - val_loss: 213.2278 - val_mean_squared_error: 213.2278
Epoch 8/25
 - 3182s - loss: 235.4133 - mean_squared_error: 235.4133 - val_loss: 195.9724 - val_mean_squared_error: 195.9724
Epoch 9/25
 - 682s - loss: 234.4271 - mean_squared_error: 234.4271 - val_loss: 218.2463 - val_mean_squared_error: 218.2463
Epoch 10/25
 - 697s - loss: 233.4278 - mean_squared_error: 233.4278 - val_loss: 193.6935 - val_mean_squared_error: 193.6935
Epoch 11/25
 - 695s - loss: 232.3895 - mean_squared_error: 232.3895 - val_loss: 199.8005 - val_mean_squared_error: 199.8005
Epoch 12/25
 - 710s - loss: 231.5881 - mean_squared_error: 231.5881 - val_loss: 203.1326 - val_mean_squared_error: 203.1326
Epoch 13/25
 - 706s - loss: 230.9435 - mean_squared_error: 230.9435 - val_loss: 263.9735 - val_mean_squared_error: 263.9735
Epoch 14/25
 - 713s - loss: 230.2354 - mean_squared_error: 230.2354 - val_loss: 227.4530 - val_mean_squared_error: 227.4530
Epoch 15/25
 - 710s - loss: 229.4040 - mean_squared_error: 229.4040 - val_loss: 231.5444 - val_mean_squared_error: 231.5444
Epoch 16/25
 - 680s - loss: 228.8768 - mean_squared_error: 228.8768 - val_loss: 222.0899 - val_mean_squared_error: 222.0899
Epoch 17/25
 - 686s - loss: 228.2568 - mean_squared_error: 228.2568 - val_loss: 274.6000 - val_mean_squared_error: 274.6000
Epoch 18/25
 - 696s - loss: 227.9266 - mean_squared_error: 227.9266 - val_loss: 217.0564 - val_mean_squared_error: 217.0564
Epoch 19/25
 - 2344s - loss: 227.4776 - mean_squared_error: 227.4776 - val_loss: 237.3355 - val_mean_squared_error: 237.3355
Epoch 20/25
 - 1790s - loss: 226.9810 - mean_squared_error: 226.9810 - val_loss: 269.8043 - val_mean_squared_error: 269.8043
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 14
