2019-05-17 17:12:29.790533: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-17 17:12:33.172689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: TITAN V major: 7 minor: 0 memoryClockRate(GHz): 1.455
pciBusID: 0000:83:00.0
totalMemory: 11.75GiB freeMemory: 11.25GiB
2019-05-17 17:12:33.172744: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-17 17:12:33.714201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-17 17:12:33.714250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-17 17:12:33.714258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-17 17:12:33.714583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10031 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:83:00.0, compute capability: 7.0)
Epoch 1/25
 - 2027s - loss: 354.1708 - mean_squared_error: 354.1708 - val_loss: 241.4855 - val_mean_squared_error: 241.4855
Epoch 2/25
 - 793s - loss: 274.1873 - mean_squared_error: 274.1873 - val_loss: 221.9505 - val_mean_squared_error: 221.9505
Epoch 3/25
 - 778s - loss: 262.0804 - mean_squared_error: 262.0804 - val_loss: 301.1879 - val_mean_squared_error: 301.1879
Epoch 4/25
 - 757s - loss: 256.7012 - mean_squared_error: 256.7012 - val_loss: 207.2508 - val_mean_squared_error: 207.2508
Epoch 5/25
 - 766s - loss: 252.7757 - mean_squared_error: 252.7757 - val_loss: 205.3424 - val_mean_squared_error: 205.3424
Epoch 6/25
 - 763s - loss: 250.1128 - mean_squared_error: 250.1128 - val_loss: 252.1818 - val_mean_squared_error: 252.1818
Epoch 7/25
 - 741s - loss: 248.4241 - mean_squared_error: 248.4241 - val_loss: 242.3699 - val_mean_squared_error: 242.3699
Epoch 8/25
 - 759s - loss: 246.9409 - mean_squared_error: 246.9409 - val_loss: 241.3100 - val_mean_squared_error: 241.3100
Epoch 9/25
 - 763s - loss: 245.3425 - mean_squared_error: 245.3425 - val_loss: 222.0615 - val_mean_squared_error: 222.0615
Epoch 10/25
 - 746s - loss: 244.0572 - mean_squared_error: 244.0572 - val_loss: 258.0716 - val_mean_squared_error: 258.0716
Epoch 11/25
 - 757s - loss: 243.3756 - mean_squared_error: 243.3756 - val_loss: 272.9753 - val_mean_squared_error: 272.9753
Epoch 12/25
 - 747s - loss: 242.6334 - mean_squared_error: 242.6334 - val_loss: 227.6585 - val_mean_squared_error: 227.6585
Epoch 13/25
 - 1726s - loss: 241.5920 - mean_squared_error: 241.5920 - val_loss: 236.5451 - val_mean_squared_error: 236.5451
Epoch 14/25
 - 1751s - loss: 240.7898 - mean_squared_error: 240.7898 - val_loss: 237.0426 - val_mean_squared_error: 237.0426
Epoch 15/25
 - 786s - loss: 239.5538 - mean_squared_error: 239.5538 - val_loss: 290.3438 - val_mean_squared_error: 290.3438
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 1
