Running from arcus-2.ics.uci.edu
2019-05-15 06:54:58.627966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX TITAN major: 3 minor: 5 memoryClockRate(GHz): 0.8755
pciBusID: 0000:02:00.0
totalMemory: 5.94GiB freeMemory: 5.87GiB
2019-05-15 06:54:58.628594: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-15 06:55:17.948278: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-15 06:55:17.948702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-15 06:55:17.948723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-15 06:55:17.949053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5662 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN, pci bus id: 0000:02:00.0, compute capability: 3.5)
{'alpha': 0.5199746599760131, 'dropout': 0.3684069047789122, 'lr': 0.008859689741949337, 'leaky_relu': 0.08683243427000087, 'batch_norm': 1, 'num_layers': 2, 'layer_0': 74, 'layer_1': 285, 'layer_2': 378, 'layer_3': 276, 'layer_4': 364, 'layer_5': 382, 'layer_6': 299, 'layer_7': 398, 'max_concurrent': 3, 'P': 'arcus_gpu.p', 'q': 'arcus.q', 'l': "hostname='(arcus-1|arcus-2|arcus-3|arcus-4|arcus-5|arcus-6|arcus-7|arcus-8|arcus-9|arcus-10)'", 'env': '/home/jott1/Projects/SHERPA_EX/.profile', 'data': 'fluxbypass_aqua', 'net_type': 'normal', 'loss_type': 'mse', 'batch_size': 2048, 'data_dir': '/baldig/chemistry/earth_system_science/', 'max_dense_layers': 8, 'epochs': 25, 'patience': 10}
Epoch 1/25
 - 4996s - loss: 466.7854 - mean_squared_error: 466.7854 - val_loss: 373.6195 - val_mean_squared_error: 373.6195
Epoch 2/25
 - 4651s - loss: 445.8591 - mean_squared_error: 445.8591 - val_loss: 384.2212 - val_mean_squared_error: 384.2212
Epoch 3/25
 - 4040s - loss: 442.7458 - mean_squared_error: 442.7458 - val_loss: 451.7810 - val_mean_squared_error: 451.7810
Epoch 4/25
 - 3854s - loss: 441.6509 - mean_squared_error: 441.6509 - val_loss: 447.5625 - val_mean_squared_error: 447.5625
Epoch 5/25
 - 4330s - loss: 441.0488 - mean_squared_error: 441.0488 - val_loss: 411.0218 - val_mean_squared_error: 411.0218
Epoch 6/25
 - 4717s - loss: 440.5146 - mean_squared_error: 440.5146 - val_loss: 435.0746 - val_mean_squared_error: 435.0746
Epoch 7/25
 - 3868s - loss: 439.9560 - mean_squared_error: 439.9560 - val_loss: 460.4556 - val_mean_squared_error: 460.4556
Epoch 8/25
 - 3691s - loss: 440.0156 - mean_squared_error: 440.0156 - val_loss: 440.2168 - val_mean_squared_error: 440.2168
Epoch 9/25
 - 3644s - loss: 439.6324 - mean_squared_error: 439.6324 - val_loss: 465.4490 - val_mean_squared_error: 465.4490
Epoch 10/25
 - 3933s - loss: 439.3026 - mean_squared_error: 439.3026 - val_loss: 443.5694 - val_mean_squared_error: 443.5694
Epoch 11/25
 - 3982s - loss: 439.2200 - mean_squared_error: 439.2200 - val_loss: 466.5296 - val_mean_squared_error: 466.5296
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 6
